package com.stayhub.canalesexternos.exception;

public enum CodigoErrorCanal {
    SOLICITUD_INVALIDA, CANAL_NO_SOPORTADO, DEPENDENCIA_NO_DISPONIBLE,
    ERROR_COMUNICACION_OTA, ERROR_COMUNICACION_PMS, RESPUESTA_EXTERNA_INVALIDA
}
