package com.stayhub.hoteles.exception;
public enum CodigoErrorHotel {
    SOLICITUD_INVALIDA, HOTEL_NO_ENCONTRADO, TIPO_HABITACION_NO_ENCONTRADO,
    HABITACION_NO_ENCONTRADA, CODIGO_DUPLICADO, NUMERO_HABITACION_DUPLICADO,
    HOTEL_INACTIVO, TIPO_HABITACION_EN_USO
}
